### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by Mistweaver**
Creates a composite action that accepts a test directory, a fixture directory, specified version of Go, specified version of terraform, and the required AWS secrets.

Addresses [Create Github Action for Running CI tests on Terraform Modules](https://github.com/synapsestudios/synapse-reference-architecture/issues/6)

### CODE REVIEW

**Review by areida — APPROVED** [review]
This looks right to me. For some reason I thought there was a separate definition like `inputs` for secrets, that doesn't seem to be the case.

**Review by spruce-bruce — COMMENTED** [review]
So this'll just be a public module? is there any value in using org workflows for this?

**Comment by Mistweaver** [comment]
@areida yeah I thought so as well (and so did Bob) but Github fails to mention in their creating actions documentation that the secrets context is unavailable [(it's buried here in the context docs)](https://docs.github.com/en/actions/learn-github-actions/contexts#secrets-context)

@spruce-bruce looks like we can make this repo `internal` vs `public` or `private`, and then under Settings > Actions > General there will be an Access menu with the option to expose the action to just the organization.   But that will have to be a you or Bob action (I don't have organization admin permissions)

**Comment by spruce-bruce** [comment]
@Mistweaver Yeah I don't think we get anything out of just making it a private action. I'm interested in stuff [like this](https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization) and maybe exploring around to see if there are other "streamline the setup of a new module" features out there for us.

I haven't read that link I just posted so it might not be germane

**Comment by Mistweaver** [comment]
@spruce-bruce Github's "official" recommendation was to let custom actions reside in their own repo.  I'm surmising their thinking is those actions can then be called in the starter workflows we setup to streamline.  Especially since we can't really pass an array of directories to an action and have it iterate, so this will have to be called similar to the use cases I added in the Readme

**Comment by Mistweaver** [comment]
Screen Shot 2022-08-10 at 12 11 30 PM

So...maybe putting this in the organizations `.github` repo (if we have one) as suggested for starter workflows - but under `/actions` - will suffice, but I am unsure

**Pull request merged**
